//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraelGeoDataModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Street
    {
        public int street_code { get; set; }
        public string street_name { get; set; }
        public string street_name_status { get; set; }
        public int official_code { get; set; }
        public int city_code { get; set; }
    
        public virtual City City { get; set; }
    }
}
