//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldGeoData
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public City()
        {
            this.City_Regions = new HashSet<City_Region>();
            this.Streets = new HashSet<Street>();
        }
    
        public int City_Code { get; set; }
        public string City_Coat_Of_Arms_110px_Link { get; set; }
        public byte[] City_Coat_Of_Arms_110px { get; set; }
        public string City_Coat_Of_Arms_110px_ext { get; set; }
        public string City_Name { get; set; }
        public string City_Name_En { get; set; }
        public string City_Name_Ru { get; set; }
        public Nullable<int> Country_Region_Code { get; set; }
        public Nullable<int> Lishkat_Mana_Code { get; set; }
        public Nullable<int> Regional_Council_Code { get; set; }
        public Nullable<int> Country_Code { get; set; }
        public string City_Link { get; set; }
        public string City_Link_En { get; set; }
        public string City_Link_Ru { get; set; }
        public string City_Description { get; set; }
        public string City_Description_En { get; set; }
        public string City_Description_Ru { get; set; }
        public Nullable<decimal> City_Latitude { get; set; }
        public Nullable<decimal> City_Longitude { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Country_Region Country_Region { get; set; }
        public virtual Lishkat_Mana Lishkat_Mana { get; set; }
        public virtual Regional_Council Regional_Council { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<City_Region> City_Regions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Street> Streets { get; set; }
    }
}
