//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldGeoData
{
    using System;
    using System.Collections.Generic;
    
    public partial class City_Region
    {
        public int City_Region_Id { get; set; }
        public string City_Region_Name { get; set; }
        public string City_Region_Name_En { get; set; }
        public string City_Region_Name_Ru { get; set; }
        public Nullable<int> City_Code { get; set; }
        public Nullable<decimal> City_Region_Latitude { get; set; }
        public Nullable<decimal> City_Region_Longitude { get; set; }
    
        public virtual City City { get; set; }
    }
}
