//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldGeoData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Country()
        {
            this.Cities = new HashSet<City>();
            this.Country_States = new HashSet<Country>();
            this.Country_Regions = new HashSet<Country_Region>();
        }
    
        public int Country_Code { get; set; }
        public string Country_Flag_22px_Link { get; set; }
        public byte[] Country_Flag_Pic_22px { get; set; }
        public string Country_Flag_Pic_22px_ext { get; set; }
        public string Country_Flag_800px_Link { get; set; }
        public byte[] Country_Flag_Pic_800px { get; set; }
        public string Country_Flag_Pic_800px_ext { get; set; }
        public string Country_Coat_Of_Arms_110px_Link { get; set; }
        public byte[] Country_Coat_Of_Arms_110px { get; set; }
        public string Country_Coat_Of_Arms_110px_ext { get; set; }
        public string Country_Name { get; set; }
        public string Country_Name_En { get; set; }
        public string Country_Name_Ru { get; set; }
        public string Country_Full_Name { get; set; }
        public string Country_Full_Name_En { get; set; }
        public string Country_Full_Name_Ru { get; set; }
        public string Country_Name_Source_Language { get; set; }
        public string Country_Link { get; set; }
        public string Country_Link_En { get; set; }
        public string Country_Link_Ru { get; set; }
        public string Country_Description { get; set; }
        public string Country_Description_En { get; set; }
        public string Country_Description_Ru { get; set; }
        public Nullable<int> Country_Capital_Constitutional_Id { get; set; }
        public Nullable<int> Country_Capital_Administrative_Id { get; set; }
        public Nullable<int> Country_Capital_Legal_Id { get; set; }
        public Nullable<int> Country_Largest_City_Population_Id { get; set; }
        public Nullable<int> Country_Largest_City_Area_Id { get; set; }
        public Nullable<int> Country_Population { get; set; }
        public Nullable<decimal> Country_Area { get; set; }
        public Nullable<decimal> Country_Density { get; set; }
        public Nullable<int> Maternal_Country_Id { get; set; }
        public string Country_Leader { get; set; }
        public string Country_Leader_En { get; set; }
        public string Country_Leader_Ru { get; set; }
        public string Country_Based { get; set; }
        public string Country_Independence_Day_From { get; set; }
        public string Country_Independence_Day_From_En { get; set; }
        public string Country_Independence_Day_From_Ru { get; set; }
        public string Country_Time_Zone { get; set; }
        public string Country_Web_Extension { get; set; }
        public string Country_Phone_Prefix { get; set; }
        public Nullable<int> Country_Status_Id { get; set; }
        public Nullable<int> UN_Member_Status_Id { get; set; }
        public Nullable<int> World_Region_Id { get; set; }
        public Nullable<decimal> Country_Latitude { get; set; }
        public Nullable<decimal> Country_Longitude { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<City> Cities { get; set; }
        public virtual City Capital_City_Administrative { get; set; }
        public virtual City Capital_City_Constitutional { get; set; }
        public virtual City Capital_City_Legal { get; set; }
        public virtual City Largest_City_Area { get; set; }
        public virtual City Largest_City_Population { get; set; }
        public virtual Country_Status Country_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Country> Country_States { get; set; }
        public virtual Country Maternal_Country { get; set; }
        public virtual UN_Member_Status UN_Member_Status { get; set; }
        public virtual World_Region World_Region { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Country_Region> Country_Regions { get; set; }
    }
}
