//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldGeoData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country_Region
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Country_Region()
        {
            this.Cities = new HashSet<City>();
        }
    
        public int Country_Region_Code { get; set; }
        public string Country_Region_Name { get; set; }
        public string Country_Region_Name_En { get; set; }
        public string Country_Region_Name_Ru { get; set; }
        public Nullable<int> Country_Code { get; set; }
        public Nullable<decimal> Country_Region_Latitude { get; set; }
        public Nullable<decimal> Country_Region_Longitude { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<City> Cities { get; set; }
        public virtual Country Country { get; set; }
    }
}
