//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldGeoData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country_Status
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Country_Status()
        {
            this.Countries = new HashSet<Country>();
        }
    
        public int Country_Status_Id { get; set; }
        public string Country_Status_Name { get; set; }
        public string Country_Status_Name_En { get; set; }
        public string Country_Status_Name_Ru { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Country> Countries { get; set; }
    }
}
