//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldGeoData
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Cities
    {
        public string טבלה { get; set; }
        public int סמל_ישוב { get; set; }
        public string שם_ישוב { get; set; }
        public string שם_ישוב_לועזי { get; set; }
        public Nullable<int> סמל_נפה { get; set; }
        public string שם_נפה { get; set; }
        public Nullable<int> סמל_לשכת_מנא { get; set; }
        public string לשכה { get; set; }
        public Nullable<int> סמל_מועצה_איזורית { get; set; }
        public string שם_מועצה { get; set; }
    }
}
