//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldGeoData
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Streets_With_Synonyms
    {
        public Nullable<int> region_code { get; set; }
        public string region_name { get; set; }
        public int City_Code { get; set; }
        public string City_Name { get; set; }
        public int Street_Code { get; set; }
        public string Street_Name { get; set; }
        public string Street_Name_Status { get; set; }
        public int official_code { get; set; }
    }
}
