//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldGeoData
{
    using System;
    using System.Collections.Generic;
    
    public partial class World_Region
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public World_Region()
        {
            this.Countries = new HashSet<Country>();
        }
    
        public int World_Region_Id { get; set; }
        public string World_Region_Name { get; set; }
        public string World_Region_Name_En { get; set; }
        public string World_Region_Name_Ru { get; set; }
        public string World_Region_Link { get; set; }
        public string World_Region_Link_En { get; set; }
        public string World_Region_Link_Ru { get; set; }
        public Nullable<decimal> World_Region_Latitude { get; set; }
        public Nullable<decimal> World_Region_Longitude { get; set; }
        public string World_Region_Description { get; set; }
        public string World_Region_Description_En { get; set; }
        public string World_Region_Description_Ru { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Country> Countries { get; set; }
    }
}
