//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraelGeoDataWPF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class IsraelGeoDataDB : DbContext
    {
        public IsraelGeoDataDB()
            : base("name=IsraelGeoDataCS")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Lishka> LishkotMana { get; set; }
        public virtual DbSet<Muaca> Muacot { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Street> Streets { get; set; }
        public virtual DbSet<View_Cities> View_Cities { get; set; }
        public virtual DbSet<View_City_Names> View_City_Names { get; set; }
        public virtual DbSet<View_Street_Names> View_Street_Names { get; set; }
        public virtual DbSet<View_Streets> View_Streets { get; set; }
    
        public virtual ObjectResult<Get_Cities_By_Lishka_Code_Result> Get_Cities_By_Lishka_Code(Nullable<int> lishkat_mana_code)
        {
            var lishkat_mana_codeParameter = lishkat_mana_code.HasValue ?
                new ObjectParameter("lishkat_mana_code", lishkat_mana_code) :
                new ObjectParameter("lishkat_mana_code", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Cities_By_Lishka_Code_Result>("Get_Cities_By_Lishka_Code", lishkat_mana_codeParameter);
        }
    
        public virtual ObjectResult<Get_Cities_By_Lishka_Name_Result> Get_Cities_By_Lishka_Name(string lishka)
        {
            var lishkaParameter = lishka != null ?
                new ObjectParameter("lishka", lishka) :
                new ObjectParameter("lishka", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Cities_By_Lishka_Name_Result>("Get_Cities_By_Lishka_Name", lishkaParameter);
        }
    
        public virtual ObjectResult<Get_Cities_By_Lishka_Name_Contains_Result> Get_Cities_By_Lishka_Name_Contains(string lishka_contains)
        {
            var lishka_containsParameter = lishka_contains != null ?
                new ObjectParameter("lishka_contains", lishka_contains) :
                new ObjectParameter("lishka_contains", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Cities_By_Lishka_Name_Contains_Result>("Get_Cities_By_Lishka_Name_Contains", lishka_containsParameter);
        }
    
        public virtual ObjectResult<Get_Cities_By_Muaca_Code_Result> Get_Cities_By_Muaca_Code(Nullable<int> muaca_ezorit_code)
        {
            var muaca_ezorit_codeParameter = muaca_ezorit_code.HasValue ?
                new ObjectParameter("muaca_ezorit_code", muaca_ezorit_code) :
                new ObjectParameter("muaca_ezorit_code", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Cities_By_Muaca_Code_Result>("Get_Cities_By_Muaca_Code", muaca_ezorit_codeParameter);
        }
    
        public virtual ObjectResult<Get_Cities_By_Muaca_Name_Result> Get_Cities_By_Muaca_Name(string muaca_name)
        {
            var muaca_nameParameter = muaca_name != null ?
                new ObjectParameter("muaca_name", muaca_name) :
                new ObjectParameter("muaca_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Cities_By_Muaca_Name_Result>("Get_Cities_By_Muaca_Name", muaca_nameParameter);
        }
    
        public virtual ObjectResult<Get_Cities_By_Muaca_Name_Contains_Result> Get_Cities_By_Muaca_Name_Contains(string muaca_name_contains)
        {
            var muaca_name_containsParameter = muaca_name_contains != null ?
                new ObjectParameter("muaca_name_contains", muaca_name_contains) :
                new ObjectParameter("muaca_name_contains", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Cities_By_Muaca_Name_Contains_Result>("Get_Cities_By_Muaca_Name_Contains", muaca_name_containsParameter);
        }
    
        public virtual ObjectResult<Get_Cities_By_Name_Contains_Result> Get_Cities_By_Name_Contains(string city_name_contains)
        {
            var city_name_containsParameter = city_name_contains != null ?
                new ObjectParameter("city_name_contains", city_name_contains) :
                new ObjectParameter("city_name_contains", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Cities_By_Name_Contains_Result>("Get_Cities_By_Name_Contains", city_name_containsParameter);
        }
    
        public virtual ObjectResult<Get_Cities_By_Name_Foreign_Contains_Result> Get_Cities_By_Name_Foreign_Contains(string city_name_foreign_contains)
        {
            var city_name_foreign_containsParameter = city_name_foreign_contains != null ?
                new ObjectParameter("city_name_foreign_contains", city_name_foreign_contains) :
                new ObjectParameter("city_name_foreign_contains", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Cities_By_Name_Foreign_Contains_Result>("Get_Cities_By_Name_Foreign_Contains", city_name_foreign_containsParameter);
        }
    
        public virtual ObjectResult<Get_Cities_By_Region_Code_Result> Get_Cities_By_Region_Code(Nullable<int> region_code)
        {
            var region_codeParameter = region_code.HasValue ?
                new ObjectParameter("region_code", region_code) :
                new ObjectParameter("region_code", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Cities_By_Region_Code_Result>("Get_Cities_By_Region_Code", region_codeParameter);
        }
    
        public virtual ObjectResult<Get_Cities_By_Region_Name_Result> Get_Cities_By_Region_Name(string region_name)
        {
            var region_nameParameter = region_name != null ?
                new ObjectParameter("region_name", region_name) :
                new ObjectParameter("region_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Cities_By_Region_Name_Result>("Get_Cities_By_Region_Name", region_nameParameter);
        }
    
        public virtual ObjectResult<Get_Cities_By_Region_Name_Contains_Result> Get_Cities_By_Region_Name_Contains(string region_name_contains)
        {
            var region_name_containsParameter = region_name_contains != null ?
                new ObjectParameter("region_name_contains", region_name_contains) :
                new ObjectParameter("region_name_contains", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Cities_By_Region_Name_Contains_Result>("Get_Cities_By_Region_Name_Contains", region_name_containsParameter);
        }
    
        public virtual ObjectResult<Get_City_By_Code_Result> Get_City_By_Code(Nullable<int> city_code)
        {
            var city_codeParameter = city_code.HasValue ?
                new ObjectParameter("city_code", city_code) :
                new ObjectParameter("city_code", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_City_By_Code_Result>("Get_City_By_Code", city_codeParameter);
        }
    
        public virtual ObjectResult<Get_City_By_Name_Result> Get_City_By_Name(string city_name)
        {
            var city_nameParameter = city_name != null ?
                new ObjectParameter("city_name", city_name) :
                new ObjectParameter("city_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_City_By_Name_Result>("Get_City_By_Name", city_nameParameter);
        }
    
        public virtual ObjectResult<Get_City_By_Name_Foreign_Result> Get_City_By_Name_Foreign(string city_name_foreign)
        {
            var city_name_foreignParameter = city_name_foreign != null ?
                new ObjectParameter("city_name_foreign", city_name_foreign) :
                new ObjectParameter("city_name_foreign", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_City_By_Name_Foreign_Result>("Get_City_By_Name_Foreign", city_name_foreignParameter);
        }
    
        public virtual ObjectResult<string> Get_City_Names()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Get_City_Names");
        }
    
        public virtual ObjectResult<string> Get_City_Names_Foreign()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Get_City_Names_Foreign");
        }
    
        public virtual ObjectResult<Get_Street_By_Code_Result> Get_Street_By_Code(Nullable<int> street_code)
        {
            var street_codeParameter = street_code.HasValue ?
                new ObjectParameter("street_code", street_code) :
                new ObjectParameter("street_code", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Street_By_Code_Result>("Get_Street_By_Code", street_codeParameter);
        }
    
        public virtual ObjectResult<Get_Street_By_Name_And_City_Code_Result> Get_Street_By_Name_And_City_Code(string street_name, Nullable<int> city_code)
        {
            var street_nameParameter = street_name != null ?
                new ObjectParameter("street_name", street_name) :
                new ObjectParameter("street_name", typeof(string));
    
            var city_codeParameter = city_code.HasValue ?
                new ObjectParameter("city_code", city_code) :
                new ObjectParameter("city_code", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Street_By_Name_And_City_Code_Result>("Get_Street_By_Name_And_City_Code", street_nameParameter, city_codeParameter);
        }
    
        public virtual ObjectResult<Get_Street_By_Name_And_City_Name_Result> Get_Street_By_Name_And_City_Name(string street_name, string city_name)
        {
            var street_nameParameter = street_name != null ?
                new ObjectParameter("street_name", street_name) :
                new ObjectParameter("street_name", typeof(string));
    
            var city_nameParameter = city_name != null ?
                new ObjectParameter("city_name", city_name) :
                new ObjectParameter("city_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Street_By_Name_And_City_Name_Result>("Get_Street_By_Name_And_City_Name", street_nameParameter, city_nameParameter);
        }
    
        public virtual ObjectResult<string> Get_Street_Names()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Get_Street_Names");
        }
    
        public virtual ObjectResult<Get_Streets_By_Name_Contains_And_City_Code_Result> Get_Streets_By_Name_Contains_And_City_Code(string street_name_contains, Nullable<int> city_code)
        {
            var street_name_containsParameter = street_name_contains != null ?
                new ObjectParameter("street_name_contains", street_name_contains) :
                new ObjectParameter("street_name_contains", typeof(string));
    
            var city_codeParameter = city_code.HasValue ?
                new ObjectParameter("city_code", city_code) :
                new ObjectParameter("city_code", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Streets_By_Name_Contains_And_City_Code_Result>("Get_Streets_By_Name_Contains_And_City_Code", street_name_containsParameter, city_codeParameter);
        }
    
        public virtual ObjectResult<Get_Streets_By_Name_Contains_And_City_Name_Result> Get_Streets_By_Name_Contains_And_City_Name(string street_name_contains, string city_name)
        {
            var street_name_containsParameter = street_name_contains != null ?
                new ObjectParameter("street_name_contains", street_name_contains) :
                new ObjectParameter("street_name_contains", typeof(string));
    
            var city_nameParameter = city_name != null ?
                new ObjectParameter("city_name", city_name) :
                new ObjectParameter("city_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Streets_By_Name_Contains_And_City_Name_Result>("Get_Streets_By_Name_Contains_And_City_Name", street_name_containsParameter, city_nameParameter);
        }
    
        public virtual ObjectResult<Get_Streets_By_Name_Contains_And_City_Name_Contains_Result> Get_Streets_By_Name_Contains_And_City_Name_Contains(string street_name_contains, string city_name_contains)
        {
            var street_name_containsParameter = street_name_contains != null ?
                new ObjectParameter("street_name_contains", street_name_contains) :
                new ObjectParameter("street_name_contains", typeof(string));
    
            var city_name_containsParameter = city_name_contains != null ?
                new ObjectParameter("city_name_contains", city_name_contains) :
                new ObjectParameter("city_name_contains", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Streets_By_Name_Contains_And_City_Name_Contains_Result>("Get_Streets_By_Name_Contains_And_City_Name_Contains", street_name_containsParameter, city_name_containsParameter);
        }
    
        public virtual int INSERT_UPDATE_City(Nullable<int> city_code, string city_name, string city_name_foreign, Nullable<int> region_code, Nullable<int> lishkat_mana_code, Nullable<int> muaca_ezorit_code)
        {
            var city_codeParameter = city_code.HasValue ?
                new ObjectParameter("city_code", city_code) :
                new ObjectParameter("city_code", typeof(int));
    
            var city_nameParameter = city_name != null ?
                new ObjectParameter("city_name", city_name) :
                new ObjectParameter("city_name", typeof(string));
    
            var city_name_foreignParameter = city_name_foreign != null ?
                new ObjectParameter("city_name_foreign", city_name_foreign) :
                new ObjectParameter("city_name_foreign", typeof(string));
    
            var region_codeParameter = region_code.HasValue ?
                new ObjectParameter("region_code", region_code) :
                new ObjectParameter("region_code", typeof(int));
    
            var lishkat_mana_codeParameter = lishkat_mana_code.HasValue ?
                new ObjectParameter("lishkat_mana_code", lishkat_mana_code) :
                new ObjectParameter("lishkat_mana_code", typeof(int));
    
            var muaca_ezorit_codeParameter = muaca_ezorit_code.HasValue ?
                new ObjectParameter("muaca_ezorit_code", muaca_ezorit_code) :
                new ObjectParameter("muaca_ezorit_code", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_UPDATE_City", city_codeParameter, city_nameParameter, city_name_foreignParameter, region_codeParameter, lishkat_mana_codeParameter, muaca_ezorit_codeParameter);
        }
    
        public virtual int INSERT_UPDATE_Lishka(Nullable<int> lishkat_mana_code, string lishka)
        {
            var lishkat_mana_codeParameter = lishkat_mana_code.HasValue ?
                new ObjectParameter("lishkat_mana_code", lishkat_mana_code) :
                new ObjectParameter("lishkat_mana_code", typeof(int));
    
            var lishkaParameter = lishka != null ?
                new ObjectParameter("lishka", lishka) :
                new ObjectParameter("lishka", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_UPDATE_Lishka", lishkat_mana_codeParameter, lishkaParameter);
        }
    
        public virtual int INSERT_UPDATE_Muaca(Nullable<int> muaca_ezorit_code, string muaca_name)
        {
            var muaca_ezorit_codeParameter = muaca_ezorit_code.HasValue ?
                new ObjectParameter("muaca_ezorit_code", muaca_ezorit_code) :
                new ObjectParameter("muaca_ezorit_code", typeof(int));
    
            var muaca_nameParameter = muaca_name != null ?
                new ObjectParameter("muaca_name", muaca_name) :
                new ObjectParameter("muaca_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_UPDATE_Muaca", muaca_ezorit_codeParameter, muaca_nameParameter);
        }
    
        public virtual int INSERT_UPDATE_Region(Nullable<int> region_code, string region_name)
        {
            var region_codeParameter = region_code.HasValue ?
                new ObjectParameter("region_code", region_code) :
                new ObjectParameter("region_code", typeof(int));
    
            var region_nameParameter = region_name != null ?
                new ObjectParameter("region_name", region_name) :
                new ObjectParameter("region_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_UPDATE_Region", region_codeParameter, region_nameParameter);
        }
    
        public virtual int INSERT_UPDATE_Street(Nullable<int> street_code, string street_name, string street_name_status, Nullable<int> official_code, Nullable<int> city_code)
        {
            var street_codeParameter = street_code.HasValue ?
                new ObjectParameter("street_code", street_code) :
                new ObjectParameter("street_code", typeof(int));
    
            var street_nameParameter = street_name != null ?
                new ObjectParameter("street_name", street_name) :
                new ObjectParameter("street_name", typeof(string));
    
            var street_name_statusParameter = street_name_status != null ?
                new ObjectParameter("street_name_status", street_name_status) :
                new ObjectParameter("street_name_status", typeof(string));
    
            var official_codeParameter = official_code.HasValue ?
                new ObjectParameter("official_code", official_code) :
                new ObjectParameter("official_code", typeof(int));
    
            var city_codeParameter = city_code.HasValue ?
                new ObjectParameter("city_code", city_code) :
                new ObjectParameter("city_code", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_UPDATE_Street", street_codeParameter, street_nameParameter, street_name_statusParameter, official_codeParameter, city_codeParameter);
        }
    }
}
