//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraelGeoDataWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Streets
    {
        public int street_code { get; set; }
        public string street_name { get; set; }
        public string street_name_status { get; set; }
        public int official_code { get; set; }
        public int city_code { get; set; }
        public string city_name { get; set; }
        public Nullable<int> region_code { get; set; }
        public string region_name { get; set; }
    }
}
